### ISSUE TITLE
[Feat] 유저 정보 조회 검색 로직 구현 

### ISSUE THREAD

**Issue by dmdgpdi** [Kernel360/hackathon2-loltfolio#44]
## 시나리오
1. 사용자는 자신의 고유한 gamename과 tagline를 입력한다.  ex) 스망클고링#KR1
2. 닉네임과 태그 번호를 이용해, API를 요청, 사용자의 입력이 올바른지 확인한다.
3. 만약 입력이 올바르다면 유저 정보 조회 페이지(메인)으로 이동한다.

**Comment by godhyzzang** [comment]
상태관리 라이브러리 ??

**Comment by godhyzzang** [comment]
.
